source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ReactiveRealm_Example' do
  pod 'ReactiveRealm', :path => '../'
  pod 'RxSwift', '~> 2.5.0'
  pod 'RealmSwift', '~> 1.0.0'
  pod 'RxCocoa', '~> 2.5.0'
end
